apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: dockerabbaas/node-app:{{BUILD_NUMBER}}
      ports:
        - containerPort: 8080
